config/routes.rb
Rails.application.routes.draw do
  
  get 'cardapios/new'

  get 'sessions/new'

  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/edit_user/:id' => 'users#edit_user'
  resources :users
  
  get '/product', to: 'products#new'
  get '/products', to: 'products#index'
  get  '/edit_product/:id', to: 'products#edit_product'
  get '/products/:id', to: 'products#show'
  resources :products
  
  get '/cardapio', to: 'cardapios#new'
  get  '/edit_cardapio/:id', to: 'cardapios#edit_cardapio'
  resources :cardapios
  
  end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates(:name, presence: true, length: { maximum: 50 })
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false})
    validates(:phone, presence: true, length: { maximum: 10 })
    validates(:register, presence: true, length: { maximum: 11 })
    validates(:cpf, presence: true, length: { maximum: 11 })
    validates(:role, presence: true, length: { maximum: 50 })
    validates(:adm, length: { maximum: 10 })
    has_secure_password
    validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true)
    
    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
   def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Usuário cadastrado com sucesso!"
      redirect_to @user
    else
      render 'new'
    end
   end
   
  def edit
    @user = User.find(params[:id])
    render :edit
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Informações do usuário editadas com sucesso!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Funcionário deletado da base de dados."
    redirect_to users_url
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :register, :phone, :cpf,
                                   :role)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Por favor, faça login."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
     # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<table class="table table-hover">
<tbody>
  <tr>
    <td><%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %></td>
    <% if current_user.admin? && !current_user?(user) %>
      <td><%= link_to "Editar", edit_user_path(user), class: "editar" %>
    <% end %>
    <% if current_user.admin? && !current_user?(user) %>
     <%= link_to "Excluir", user, method: :delete,
                                  data: { confirm: "You sure?" }, class: "excluir" %></td>
    <% end %>
  </tr>
</tbody>
</table>

app/views/users/edit.html.erb
<% provide(:title, "Editar usuário") %>
<h1>Editar informações do usuário</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone, 'Telefone' %>
      <%= f.phone_field :phone, class: 'form-control' %>
      
      <%= f.label :register, 'Número de registro' %>
      <%= f.phone_field :register, class: 'form-control' %>
      
      <%= f.label :cpf, 'CPF' %>
      <%= f.text_field :cpf, class: 'form-control' %>
      
      <%= f.label :role, 'Cargo' %>
      <%= f.text_field :role, class: 'form-control' %>
      
      <% if current_user?(@user) %>
      <%= f.label :password, 'Senha' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmar senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <% end %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuários') %>
<h1>Usuários</h1>

<%= link_to "Cadastrar funcionário", signup_path, class: 'cadastrarfuncionario' %>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Cadastro de Funcionários') %>
<h1>Cadastro de Funcionários</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages_user' %>
    
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone, 'Telefone' %>
      <%= f.phone_field :phone, class: 'form-control' %>
      
      <%= f.label :register, 'Número de registro' %>
      <%= f.phone_field :register, class: 'form-control' %>
      
      <%= f.label :cpf, 'CPF' %>
      <%= f.text_field :cpf, class: 'form-control' %>
      
      <%= f.label :role, 'Cargo' %>
      <%= f.text_field :role, class: 'form-control' %>
      
      <%= f.label :password, 'Senha' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'Confirmar senha' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Cadastrar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--<div class="profileimage">
  <h1><%= gravatar_for @user %></>
</div>-->

<div class="username">
  <h1><%= @user.name %></h1>
</div>

<div class="role">
  <p><%= @user.role %></p>
</div>

<ul class="list-group">
  <p class="nome">email</p>
  <li class="list-group-item"><%= @user.email %></li>
</ul>

<ul class="list-group">
  <p class="nome">telefone</p>
  <li class="list-group-item"><%= @user.phone %></li>
</ul>

<ul class="list-group">
  <p class="nome">número de registro</p>
  <li class="list-group-item"><%= @user.register %></li>
</ul>

<ul class="list-group">
  <p class="nome">cpf</p>
  <li class="list-group-item"><%= @user.cpf %></li>
</ul>