config/routes.rb
Rails.application.routes.draw do
  
  get 'cardapios/new'

  get 'sessions/new'

  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/edit_user/:id' => 'users#edit_user'
  resources :users
  
  get '/product', to: 'products#new'
  get '/products', to: 'products#index'
  get  '/edit_product/:id', to: 'products#edit_product'
  get '/products/:id', to: 'products#show'
  resources :products
  
  get '/cardapio', to: 'cardapios#new'
  get  '/edit_cardapio/:id', to: 'cardapios#edit_cardapio'
  resources :cardapios
  
  end

app/models/product.rb
class Product < ApplicationRecord
    validates(:name, presence: true, length: { maximum: 50 })
    validates(:storage, presence: true, length: { maximum: 50 })
    validates(:perishability, presence: true, length: { maximum: 50 })
    validates(:weightandquant, presence: true, length: { maximum: 50 })
    validates(:price, presence: true, length: { maximum: 7 })
    validates(:furnisher, presence: true, length: { maximum: 50 })
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.paginate(page: params[:page])
  end

  
  def new
    @product = Product.new
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
   def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Produto cadastrado com sucesso!"
      redirect_to products_url
    else
      render 'new'
    end
   end
   
  def edit
    @product = Product.find(params[:id])
    render :edit
  end
  
  def update
  respond_to do |format|
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Produto editado com sucesso"
      redirect_to @products
    else
      render :edit
    end
  end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "Produto deletado"
    redirect_to products_url
  end
  
  

  private

  def product_params
      params.require(:product).permit(:name, :storage, :perishability,
                                      :weightandquant, :price, :furnisher)
  end
  
  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
   
end

app/views/products/_product.html.erb
<table class="table table-hover">
<tbody>
  <tr>
    <td><%= link_to product.name, product %></td>
    <% if current_user.admin? %>
        <td><%= link_to "Editar", edit_product_path(product), class: "editar" %>
    <% end %>
    <% if current_user.admin? %>
       <%= link_to "Excluir",{ action: :destroy, id: product.id }, method: :delete,
              data: { confirm: "You sure?" }, class: "excluir" %></td>
    <% end %>
  </tr>
</tbody>
</table>
    

app/views/products/edit.html.erb
<% provide(:title, "Editar produto") %>
<h1>Editar produto</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>

      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :storage, 'Local de armazenamento' %>
      <%= f.text_field :storage, class: 'form-control' %>
      
      <%= f.label :perishability, 'Perecibilidade' %>
      <%= f.text_field :perishability, class: 'form-control' %>
      
      <%= f.label :weightandquant, 'Peso ou quantidade' %>
      <%= f.text_field :weightandquant, class: 'form-control' %>
      
      <%= f.label :price, 'Preço' %>
      <%= f.text_field :price, class: 'form-control' %>
      
      <%= f.label :furnisher, 'Fornecedor' %>
      <%= f.text_field :furnisher, class: 'form-control' %>

      <%= f.submit "Salvar", class: "btn btn-primary" %>
      
      <li>
        <%= link_to "Cadastrar qualidade", class: 'qualidade' %>
        <%= link_to "Consultar qualidade", class: 'qualidade' %>
      </li>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, 'Lista de produtos') %>
<h1>Lista de Produtos</h1>

<%= link_to "Cadastrar produto", product_path, class: 'cadastrarproduto' %>

<%= will_paginate %>

<ul class="users">
  <%= render @products %>
</ul>

<%= will_paginate %>

app/views/products/new.html.erb
<% provide(:title, 'Cadastrar Produto') %>
<h1>Cadastrar Produto</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
    <%= render 'shared/error_messages_product' %>
    
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :storage, 'Local de armazenamento' %>
      <%= f.text_field :storage, class: 'form-control' %>
      
      <%= f.label :perishability, 'Perecibilidade' %>
      <%= f.text_field :perishability, class: 'form-control' %>
      
      <%= f.label :weightandquant, 'Peso ou quantidade' %>
      <%= f.text_field :weightandquant, class: 'form-control' %>
      
      <%= f.label :price, 'Preço' %>
      <%= f.text_field :price, class: 'form-control' %>
      
      <%= f.label :furnisher, 'Fornecedor' %>
      <%= f.text_field :furnisher, class: 'form-control' %>
      
      <%= f.submit "Cadastrar produto", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<!-- precisa linkar ainda -->

app/views/products/show.html.erb
  
<%= @product.name %>, <%= @product.storage %>, <%= @product.perishability %>, 
<%= @product.weightandquant %>, <%= @product.price %>, <%= @product.furnisher %>