config/routes.rb
Rails.application.routes.draw do
  
  get 'cardapios/new'

  get 'sessions/new'

  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/edit_user/:id' => 'users#edit_user'
  resources :users
  
  get '/product', to: 'products#new'
  get '/products', to: 'products#index'
  get  '/edit_product/:id', to: 'products#edit_product'
  get '/products/:id', to: 'products#show'
  resources :products
  
  get '/cardapio', to: 'cardapios#new'
  get  '/edit_cardapio/:id', to: 'cardapios#edit_cardapio'
  resources :cardapios
  
  end

app/models/cardapio.rb
class Cardapio < ApplicationRecord
    validates :nome, presence: true, length: { maximum: 50 }
    validates :descricao, presence: true, length: { maximum: 350 }
    validates :preco, presence: true, length: { maximum: 50 }
end

app/controllers/cardapios_controller.rb
class CardapiosController < ApplicationController
  
  def index
    @cardapios = Cardapio.paginate(page: params[:page])
  end
  
  def show
    @cardapio = Cardapio.find(params[:id])
  end
  
  def new
    @cardapio = Cardapio.new
  end
  
  def create
    @cardapio = Cardapio.new(cardapio_params)    
    if @cardapio.save
      flash[:success] = "Item adicionado com sucesso"
      redirect_to cardapio_url
    else
      render 'new'
    end
  end
  
  def edit
    @cardapio = Cardapio.find(params[:id])
  end
  
  def update
    @cardapio = Cardapio.find(params[:id])
    if @cardapio.update_attributes(cardapio_params)
      flash[:success] = "Item editado com sucesso"
      redirect_to @cardapio
    else
      render 'edit'
    end
  end
  
   def destroy
    Cardapio.find(params[:id]).destroy
    flash[:success] = "Item deletado"
    redirect_to cardapios_url
   end
  
   private

    def cardapio_params
      params.require(:cardapio).permit(:nome, :descricao, :preco )
    end
  
end

app/helpers/cardapios_helper.rb
module CardapiosHelper
end

app/views/cardapios/_cardapio.html.erb
<table class="table table-hover">
<tbody>
  <tr>
    <td><%= link_to cardapio.nome, cardapio %></td>
    <% if current_user.admin?%>
        <td><%= link_to "Editar", edit_cardapio_path(cardapio), class: "editar" %>
    <% end %>
    <% if current_user.admin? %>
       <%= link_to "Excluir",{ action: :destroy, id: cardapio.id }, method: :delete,
              data: { confirm: "You sure?" }, class: "excluir" %></td>
    <% end %>
  </tr>
</tbody>
</table>
    

app/views/cardapios/edit.html.erb
<% provide(:title, "Editar item do cardápio") %>
<h1>Editar item do cardápio</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@cardapio) do |f| %>
      <%= render 'shared/error_messages_cardapio' %>

      <%= f.label :nome, 'Nome' %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :descricao, 'Descrição' %>
      <%= f.text_field :descricao, class: 'form-control' %>

      <%= f.label :preco, 'Preço' %>
      <%= f.text_field :preco, class: 'form-control' %>

      <%= f.submit "Salvar alterações", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cardapios/index.html.erb
<% provide(:title, 'Itens do Cardápio') %>
<h1>Itens do Cardápio</h1>

<%= link_to "Cadastrar item no cardápio", cardapio_path, class: 'cadastrarcardapio' %>

<%= will_paginate %>
<ul class="users">
   <%= render @cardapios %>
</ul>

app/views/cardapios/new.html.erb
<% provide(:title, 'Cadastre item no cardápio') %>
<h1>Cadastre item no cardápio</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@cardapio) do |f| %>
    <%= render 'shared/error_messages_cardapio' %>
    
      <%= f.label :nome, 'Nome' %>
      <%= f.text_field :nome, class: 'form-control' %>

      <%= f.label :descricao, 'Descrição' %>
      <%= f.text_field :descricao, class: 'form-control' %>

      <%= f.label :preco, 'Preço' %>
      <%= f.text_field :preco, class: 'form-control' %>
      
      <%= f.submit "Cadastrar item", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cardapios/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @cardapio.name %>
      </h1>
    </section>
  </aside>
</div>      
      <%= @cardapio.descricao %>, <%= @cardapio.preco %>