config/routes.rb
Rails.application.routes.draw do
  
  get 'cardapios/new'

  get 'sessions/new'

  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/edit_user/:id' => 'users#edit_user'
  resources :users
  
  get '/product', to: 'products#new'
  get '/products', to: 'products#index'
  get  '/edit_product/:id', to: 'products#edit_product'
  get '/products/:id', to: 'products#show'
  resources :products
  
  get '/cardapio', to: 'cardapios#new'
  get  '/edit_cardapio/:id', to: 'cardapios#edit_cardapio'
  resources :cardapios
  
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ©Pracinha Bar - Por Agnes Travalon e Giovanna Capel
  </small>
  <nav>
    <ul>
      <li><%= link_to "Ajuda",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light" style="background-color: #00CED1;">
  <div class="container">
    <%= link_to "pracinha bar", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? && current_user.admin? %>
          <li><%= link_to "Funcionários", users_path, class: 'nav-link' %></li>
          <li><%= link_to "Produtos", products_path, class: 'nav-link' %></li>
          <li><%= link_to "Cardápio", cardapios_path, class: 'nav-link' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Conta <b class="caret"></b>
            </a> 
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sair", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        
        <% elsif logged_in? %>
          <li><%= link_to "Pedido", '#', class: 'nav-link' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown", class="nav-link">
              Conta <b class="caret"></b>
            </a> 
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sair", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Pracinha Bar</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>